### ISSUE TITLE
html参数

### ISSUE THREAD

**Issue by MinjieChang** [falost/node-puppeteer-poster#3]
你好，请教一下，这段代码
async handleSnapshot () {
    **let html = this.ctx.query.html**
    let htmlRedisKey = createHash('sha256').update(html).digest('hex')
    return await this.generateSnapshot(htmlRedisKey)
 }
html参数传的是什么，最后生成了文末的你的博客截图，是dom字符串，还是url地址

**Comment by falost** [comment]
我这里是传的 dom 字符串，当然你也可以使用 url 获取到 dom节点来生成

**Comment by MinjieChang** [comment]
dom 字符串 css样式是怎么处理的，能贴个示例么

**Comment by falost** [comment]
> dom 字符串 css样式是怎么处理的，能贴个示例么

可以内链  也可以通过 URL 引入，我是直接复制我的 博客首页的源代码的，不过 DOM 的大小影响绘制时间

**Comment by MinjieChang** [comment]
哦哦，好的，谢谢 👍

**Comment by yongbingcao** [comment]
> > dom 字符串 css样式是怎么处理的，能贴个示例么
> 
> 可以内链 也可以通过 URL 引入，我是直接复制我的 博客首页的源代码的，不过 DOM 的大小影响绘制时间
@falost  大佬，想问一下 支持vue的vant组件吗

> 我这里是传的 dom 字符串，当然你也可以使用 url 获取到 dom节点来生成

大佬 想问下vue的vant组件dom字符串，能识别支持吗
